### ISSUE TITLE
LEDs won't turn on.

### ISSUE THREAD

**Issue by marrobHD** [EricHigdon/OctoPrint-RGB_status#8]
My WS2812B, WS2812 and WS2811 LEDs won't turn on.

**Comment by EricHigdon** [comment]
@marrodHD can you share your octoprint.log? That should give me some insight into the cause of the issue.

**Comment by marrobHD** [comment]
There I have pasted the log: https://jpst.it/1DwHR

**Comment by EricHigdon** [comment]
2019-03-10 17:57:14,555 - octoprint.plugins.rgb_status - ERROR - ws2811_init failed with code -11 (Selected GPIO not possible)

Seems relevant. What do you have the LED Pin setting set to?

**Comment by marrobHD** [comment]
GPIO 13

**Comment by marrobHD** [comment]
That are my settings:
![Screenshot_8](https://user-images.githubusercontent.com/29308361/54090353-9e70bf80-4373-11e9-90d2-13777b26a997.png)

**Comment by EricHigdon** [comment]
@marrobHD Try setting LED channel to 1 and restarting

**Comment by marrobHD** [comment]
I have that before it won't work. Now the LEDs won't work like before.

**Comment by EricHigdon** [comment]
Are you running OctoPrint as root?
And is there a reason you don’t want to use pin 10?

**Comment by marrobHD** [comment]
I have installed octoprint on the sdcard directly. I have used the octoprint image.

**Comment by marrobHD** [comment]
I think that it is root right? I can use pin 10.

**Comment by EricHigdon** [comment]
OctoPrint does not run as root by default, and it is not recommended that you do so. If you have no other reason to use a different pin, I highly suggest sticking to 10.

**Comment by marrobHD** [comment]
How can I run octoprint as root. How can I change that in the image that at boot octoprint automatically boot with root. Why then do not the LEDs work on the other?

**Comment by marrobHD** [comment]
![](https://i.imgur.com/D48oIOE.png)

**Comment by EricHigdon** [comment]
@marrobHD You probably shouldn't try to run OctoPrint as root ([see here](https://community.octoprint.org/t/starting-octoprint-with-sudo-as-root-tells-me-you-should-not-run-octoprint-as-root-why/230)). 

In the image you attached, 13 would be the 4th pin from the bottom in the left column as we are looking at the BCM number.

I highly suggest switching to pin 10 since you wouldn't need to run as root. If pin 10 isn't working, make sure that you add the pi user to the gpio group, and enable SPI ([see here](https://github.com/EricHigdon/OctoPrint-RGB_status#running-without-root)).

You also may need to change your buffer size and core frequency ([see here](https://github.com/jgarff/rpi_ws281x#spi)).

If it still isn't working after following those steps, please share your octoprint.log again after rebooting.

I'm working on adding a wizard to walk new users through this stuff since it can be complicated.

**Comment by marrobHD** [comment]
MOSI is pin 10 right?

**Comment by EricHigdon** [comment]
@marrobHD Yes.

**Comment by cryoplay** [comment]
Hello there.

I have the same Problem.
Hocked up my Strip to Pin 10.
Nothing Happens. Process turns on without a Problem but i had no light.

https://justpaste.it/6wnmc

**Comment by EricHigdon** [comment]
@cryoplay From your log, it looks like everything is actually working on the software side. Do you have your LEDs attached to pin 10 and the ground pin on the pi?

**Comment by marrobHD** [comment]
It's not working

**Comment by cryoplay** [comment]
Hi Eric.

My Problem is gone.
I forgot to hook the Strip to the ground of the Pi.
Sry. im really dump.

Now all is working perfectly.

**Comment by EricHigdon** [comment]
@marrobHD can you share your OctoPrint.log again?

**Comment by marrobHD** [comment]
Here is my log: https://jpst.it/1DHLe

**Comment by EricHigdon** [comment]
@marrobHD It still says the "Selected GPIO not possible" are you sure you changed it to pin 10 in the settings and restarted?

**Comment by marrobHD** [comment]
Yes http://prntscr.com/mwy5qv

**Comment by EricHigdon** [comment]
Is the spidev device visible on your machine?
Check using:
ls /dev/spidev0.*

**Comment by marrobHD** [comment]
It is now working. I had to remove PSU control...
